[build]
  command = "npm run build"
  publish = "vue3_folder/dist"
  base = ""  # Ensure this path is correct if your Vue project is nested

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200